using SIM.Domain.Abstractions;
using SIM.Domain.Constants;
using SIM.Domain.Enums;
using SIM.Domain.Exceptions;

namespace SIM.Domain.Entities;

/// <summary>
/// Represents the application-level user profile linked to a Supabase Auth user.
/// The Id is the Supabase auth.users.id UUID — never generated by the application.
/// </summary>
public class UserProfile : IOrganizationScoped
{
    public Guid Id { get; private set; }
    public string FullName { get; private set; } = string.Empty;
    public string Email { get; private set; } = string.Empty;
    public UserRole Role { get; private set; }
    public Guid OrganizationId { get; private set; }
    public Guid? UnitId { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime? UpdatedAt { get; private set; }
    public bool IsActive { get; private set; }

    // Navigation
    public Organization? Organization { get; private set; }

    private UserProfile() { }

    public static UserProfile Create(
        Guid supabaseUserId,
        string fullName,
        string email,
        UserRole role,
        Guid organizationId,
        Guid? unitId = null)
    {
        if (supabaseUserId == Guid.Empty)
            throw new DomainValidationException(ValidationMessages.UserIdRequired);

        if (string.IsNullOrWhiteSpace(fullName))
            throw new DomainValidationException(ValidationMessages.FullNameRequired);

        if (string.IsNullOrWhiteSpace(email))
            throw new DomainValidationException(ValidationMessages.EmailRequired);

        if (organizationId == Guid.Empty)
            throw new DomainValidationException(ValidationMessages.OrganizationRequired);

        EnforceSuperAdminOrgInvariant(role, organizationId);

        return new UserProfile
        {
            Id = supabaseUserId,
            FullName = fullName.Trim(),
            Email = email.Trim().ToLowerInvariant(),
            Role = role,
            OrganizationId = organizationId,
            UnitId = unitId,
            CreatedAt = DateTime.UtcNow,
            IsActive = true
        };
    }

    public void UpdateRole(UserRole newRole)
    {
        EnforceSuperAdminOrgInvariant(newRole, OrganizationId);

        Role = newRole;
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Domain invariant: SuperAdmin users must belong to the SimSuporte organization.
    /// Enforced at creation and on every role change — no handler can bypass this.
    /// </summary>
    private static void EnforceSuperAdminOrgInvariant(UserRole role, Guid organizationId)
    {
        if (role == UserRole.SuperAdmin && organizationId != SystemOrganizations.SimSuporte)
            throw new DomainValidationException(ValidationMessages.SuperAdminMustBelongToSimSuporte);
    }

    public void Deactivate()
    {
        IsActive = false;
        UpdatedAt = DateTime.UtcNow;
    }
}
