export const queryKeys = {
  organizations: ['organizations'] as const,
  users: ['users'] as const,
  user: (id: string) => ['users', id] as const,
  units: ['units'] as const,
  unit: (id: string) => ['units', id] as const,
  unitUsers: (unitId: string) => ['units', unitId, 'users'] as const,
  categories: ['categories'] as const,
  category: (id: string) => ['categories', id] as const,
  medications: ['medications'] as const,
  medication: (id: string) => ['medications', id] as const,
  suppliers: ['suppliers'] as const,
  supplier: (id: string) => ['suppliers', id] as const,
  batches: ['batches'] as const,
  batchesByProduct: (productId: string) => ['batches', 'product', productId] as const,
}
